/**
 * cleanAITraces.ts
 * Remove rastros de IA de textos gerados — sem quebrar sintaxe ou lógica.
 * Seguro para usar em onChange/onBlur de textareas e em outputs de LLMs.
 */

// Emojis Unicode (todos os intervalos conhecidos)
const EMOJI_RE = /[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}\u{1F000}-\u{1FFFF}\u{200D}\u{20E3}\u{FE0F}\u{1F1E0}-\u{1F1FF}]/gu;

// Frases de IA em comentários ou início de linha
const AI_PHRASES_RE = /^\s*(Generated by|AI-assisted|AI generated|Copilot|ChatGPT|GPT-4|Claude:|Assistant:|Certainly!|Here's how|Below is|Let me explain|Sure,|Of course,|<AI>|\[AI\]|<!--\s*AI\s*-->)\s*/gim;

// Traços tipográficos em comentários/strings — substitui por hífen simples
const EM_DASH_RE = /[—–―]/g;

// Comentários de linha única com palavras genéricas de IA
// Cuidado: não remover "--" como operador (decremento, etc)
const AI_COMMENT_SINGLE_RE = /\/\/\s*(inicia|inicializa|define|loop|função|calcula|retorna|exemplo|nota|observação|atenção|passo|etapa|aqui|abaixo|acima|conforme|verificar?|checar?|todo|fixme|hack|review|generated|copilot|chatgpt|ai:)\b[^\n]*/gi;

// Traços longos (--) SOMENTE em comentários de linha (// ...) ou blocos (/* */)
// Deixa intacto em código real (decremento, CSS, etc)
const COMMENT_DASH_RE = /(\/\/[^\n]*?)\s*—\s*/g;

// Linhas vazias extras (3+ seguidas → 2 no máximo)
const EXTRA_BLANK_LINES_RE = /\n{3,}/g;

/**
 * Remove rastros de IA de um texto/código sem quebrar a lógica.
 * @param text — texto a limpar
 * @param options — configurações opcionais
 */
export function cleanAITraces(
  text: string,
  options: {
    removeEmojis?:   boolean; // default: true
    removeComments?: boolean; // default: true (somente comentários genéricos de IA)
    removePhrases?:  boolean; // default: true
    fixDashes?:      boolean; // default: true
    fixBlankLines?:  boolean; // default: true
  } = {}
): string {
  const {
    removeEmojis   = true,
    removeComments = true,
    removePhrases  = true,
    fixDashes      = true,
    fixBlankLines  = true,
  } = options;

  let result = text;

  // 1. Remove frases de IA no início de linhas
  if (removePhrases) {
    result = result.replace(AI_PHRASES_RE, "");
  }

  // 2. Remove comentários genéricos de IA (// inicializa, // define, etc.)
  if (removeComments) {
    result = result.replace(AI_COMMENT_SINGLE_RE, "");
  }

  // 3. Substitui traços tipográficos em comentários por hífen
  if (fixDashes) {
    result = result.replace(COMMENT_DASH_RE, (_, comment) =>
      comment.replace(EM_DASH_RE, "-")
    );
    // Traços tipográficos soltos fora de código
    result = result.replace(EM_DASH_RE, "-");
  }

  // 4. Remove emojis
  if (removeEmojis) {
    result = result.replace(EMOJI_RE, "");
  }

  // 5. Reduz linhas em branco excessivas (3+ → 2)
  if (fixBlankLines) {
    result = result.replace(EXTRA_BLANK_LINES_RE, "\n\n");
  }

  // 6. Limpa espaços extras no final de cada linha
  result = result.replace(/[ \t]+$/gm, "");

  return result.trim();
}

/**
 * Versão leve — apenas para textos de marketing/copy (não código).
 * Remove emojis, frases de IA e traços tipográficos.
 * Ideal para onChange em campos de texto da campanha.
 */
export function cleanAICopy(text: string): string {
  return cleanAITraces(text, {
    removeEmojis:   true,
    removeComments: false, // copy não tem comentários de código
    removePhrases:  true,
    fixDashes:      true,
    fixBlankLines:  true,
  });
}

/**
 * Hook para usar em onChange de textarea — throttled para não travar digitação.
 * Retorna { value, onChange } para espalhar no textarea.
 */
export function useCleanTextarea(
  value: string,
  setValue: (v: string) => void,
  mode: "copy" | "code" = "copy"
) {
  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const raw = e.target.value;
    // Só limpa quando o usuário para de digitar (onBlur vai limpar mais profundamente)
    setValue(raw);
  };

  const handleBlur = () => {
    const cleaned = mode === "code"
      ? cleanAITraces(value)
      : cleanAICopy(value);
    if (cleaned !== value) setValue(cleaned);
  };

  return { value, onChange: handleChange, onBlur: handleBlur };
}

export default cleanAITraces;
